package com.mycompany.di_p5;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Ventana principal de la aplicación, utilizada para la autenticación de usuario
 * y contraseña.
 * Oculta la ventana de login y abre la ventana de selección principal al autenticar con éxito.
 */
public class LoginFrame extends JFrame implements ActionListener {

    private JTextField userField;
    private JPasswordField passwordField;
    private JButton loginButton;

    // Credenciales correctas
    private static final String CORRECT_USER = "admin";
    private static final String CORRECT_PASS = "1234";

    /**
     * Constructor para crear la ventana de inicio de sesión.
     */
    public LoginFrame() {
        super("Inicio de Sesión - Sistema de Contenidos");

        // Configuración básica de la ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 250);
        setLayout(new BorderLayout(10, 10));
        setLocationRelativeTo(null); // Centrar la ventana

        // --- Panel para los campos de formulario ---
        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 10, 20));

        // 1. Campo de Usuario
        formPanel.add(new JLabel("Usuario:"));
        userField = new JTextField(15);
        userField.setText(CORRECT_USER); // Valor de prueba para facilitar el uso
        formPanel.add(userField);

        // 2. Campo de Contraseña (JPasswordField)
        formPanel.add(new JLabel("Contraseña:"));
        passwordField = new JPasswordField(15);
        passwordField.setText(CORRECT_PASS); // Valor de prueba para facilitar el uso
        formPanel.add(passwordField);

        // 3. Botón de Login
        loginButton = new JButton("Iniciar Sesión");
        loginButton.addActionListener(this);

        // Añadir componentes al Frame
        add(formPanel, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        buttonPanel.add(loginButton);
        add(buttonPanel, BorderLayout.SOUTH);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Maneja el evento de pulsación del botón "Iniciar Sesión".
     * Realiza la validación de las credenciales.
     * @param e El evento de acción que se ha producido.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == loginButton) {
            String user = userField.getText();
            String password = new String(passwordField.getPassword());

            if (user.equals(CORRECT_USER) && password.equals(CORRECT_PASS)) {
                // Autenticación correcta
                JOptionPane.showMessageDialog(this, "¡Bienvenido! Acceso concedido.");
                
                // Ocultar la ventana actual
                this.setVisible(false);
                this.dispose();
                
                // Abrir la ventana principal
                // Usar el mismo código que en Main.java para inicializar
                SwingUtilities.invokeLater(() -> {
                    Main.main(new String[]{});
                });
                
            } else {
                // Autenticación fallida
                JOptionPane.showMessageDialog(this, 
                    "Usuario o contraseña incorrectos.", 
                    "Error de Login", 
                    JOptionPane.ERROR_MESSAGE);
                passwordField.setText("");
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
